symptom_mapping = {
    'back pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'abdominal pain': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'pulsating abdomen': ['Localized Swelling', 'Gastrointestinal Discomfort'],
    'fainting': ['Cardiac Symptoms', 'Cognitive or Neurological Issues', 'Temperature Regulation Issues'],
    'cold limbs': ['Temperature Regulation Issues', 'Cardiac Symptoms'],
    'heel pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'stiffness': ['Mobility and Muscular Issues'],
    'swelling': ['Localized Swelling'],
    'tenderness': ['Localized Tenderness', 'Localized Pain'],
    'difficulty walking': ['Mobility and Muscular Issues'],
    'pimples': ['Skin Irritation or Abnormalities'],
    'blackheads': ['Skin Irritation or Abnormalities'],
    'whiteheads': ['Skin Irritation or Abnormalities'],
    'redness': ['Skin Irritation or Abnormalities'],
    'inflammation': ['Skin Irritation or Abnormalities', 'Localized Swelling'],
    'scarring': ['Skin Irritation or Abnormalities'],
    'upper-right abdomen pain': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'nausea': ['Gastrointestinal Discomfort'],
    'vomiting': ['Gastrointestinal Discomfort'],
    'fever': ['Temperature Regulation Issues', 'Infections'],
    'jaundice': ['Skin Irritation or Abnormalities', 'Bleeding or Blood-Related Symptoms'],
    'fatigue': ['Fatigue or Low Energy'],
    'infections': ['Infections'],
    'bruising': ['Bleeding or Blood-Related Symptoms', 'Skin Irritation or Abnormalities'],
    'bleeding gums': ['Bleeding or Blood-Related Symptoms'],
    'bone pain': ['Localized Pain'],
    'swollen lymph nodes': ['Localized Swelling', 'Infections'],
    'pale skin': ['Skin Irritation or Abnormalities', 'Bleeding or Blood-Related Symptoms'],
    'easy bruising': ['Bleeding or Blood-Related Symptoms', 'Skin Irritation or Abnormalities'],
    'swollen belly': ['Localized Swelling'],
    'bleeding': ['Bleeding or Blood-Related Symptoms'],
    'weight loss': ['Appetite and Weight Changes', 'Fatigue or Low Energy'],
    'nosebleeds': ['Bleeding or Blood-Related Symptoms'],
    'swollen gums': ['Localized Swelling', 'Bleeding or Blood-Related Symptoms'],
    'frequent infections': ['Infections'],
    'upper abdominal pain': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'bloating': ['Gastrointestinal Discomfort'],
    'rapid heartbeat': ['Cardiac Symptoms'],
    'darkened skin': ['Skin Irritation or Abnormalities'],
    'low blood pressure': ['Cardiac Symptoms'],
    'muscle weakness': ['Mobility and Muscular Issues'],
    'salt craving': ['Miscellaneous'],
    'heavy periods': ['Bleeding or Blood-Related Symptoms'],
    'pelvic pain': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'cramping': ['Mobility and Muscular Issues', 'Localized Pain'],
    'pain during intercourse': ['Localized Pain'],
    'sneezing': ['Respiratory Issues'],
    'runny nose': ['Respiratory Issues'],
    'nasal congestion': ['Respiratory Issues'],
    'itchy eyes': ['Sensory Issues', 'Vision and Hearing Issues'],
    'watery eyes': ['Sensory Issues', 'Vision and Hearing Issues'],
    'cough': ['Respiratory Issues'],
    'rash': ['Skin Irritation or Abnormalities'],
    'itchy skin': ['Skin Irritation or Abnormalities'],
    'wheezing': ['Respiratory Issues'],
    'memory loss': ['Cognitive or Neurological Issues'],
    'confusion': ['Cognitive or Neurological Issues'],
    'mood changes': ['Mood and Behavioral Change'],
    'difficulty speaking': ['Cognitive or Neurological Issues'],
    'impaired reasoning': ['Cognitive or Neurological Issues'],
    'disorientation': ['Cognitive or Neurological Issues'],
    'rectal bleeding': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'pain': ['Localized Pain'],
    'itching': ['Skin Irritation or Abnormalities'],
    'lumps': ['Localized Swelling'],
    'discharge': ['Bowel and Bladder Issues'],
    'bowel changes': ['Bowel and Bladder Issues'],
    'difficulty breathing': ['Respiratory Issues'],
    'dizziness': ['Cognitive or Neurological Issues', 'Cardiac Symptoms'],
    'chest pain': ['Localized Pain', 'Cardiac Symptoms', 'Respiratory Issues'],
    'shortness of breath': ['Respiratory Issues', 'Cardiac Symptoms'],
    'sweating': ['Temperature Regulation Issues'],
    'joint pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'vision problems': ['Vision and Hearing Issues'],
    'hair loss': ['Hair and Nail Abnormalities'],
    'brittle nails': ['Hair and Nail Abnormalities'],
    'cold intolerance': ['Temperature Regulation Issues'],
    'restlessness': ['Mood and Behavioral Change'],
    'irritability': ['Mood and Behavioral Change'],
    'chest tightness': ['Respiratory Issues', 'Cardiac Symptoms'],
    'racing heart': ['Cardiac Symptoms'],
    'fear': ['Mood and Behavioral Change'],
    'stomach aches': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'refusal to attend school': ['Mood and Behavioral Change'],
    'crying': ['Mood and Behavioral Change'],
    'difficulty sleeping': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'constipation': ['Bowel and Bladder Issues'],
    'limb pain': ['Localized Pain'],
    'numbness': ['Cognitive or Neurological Issues', 'Sensory Issues'],
    'weakness': ['Mobility and Muscular Issues'],
    'poor coordination': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'slurred speech': ['Cognitive or Neurological Issues'],
    'tremors': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'dryness': ['Skin Irritation or Abnormalities'],
    'cracking': ['Skin Irritation or Abnormalities'],
    'oozing': ['Skin Irritation or Abnormalities'],
    'irregular heartbeat': ['Cardiac Symptoms'],
    'palpitations': ['Cardiac Symptoms'],
    'inattention': ['Cognitive or Neurological Issues', 'Mood and Behavioral Change'],
    'hyperactivity': ['Mood and Behavioral Change'],
    'impulsiveness': ['Mood and Behavioral Change'],
    'fidgeting': ['Mood and Behavioral Change'],
    'forgetfulness': ['Cognitive or Neurological Issues'],
    'difficulty focusing': ['Cognitive or Neurological Issues'],
    'social difficulties': ['Mood and Behavioral Change', 'Cognitive or Neurological Issues'],
    'repetitive behaviors': ['Mood and Behavioral Change', 'Cognitive or Neurological Issues'],
    'speech delay': ['Developmental Issues'],
    'sensory sensitivity': ['Sensory Issues'],
    'restricted interests': ['Mood and Behavioral Change', 'Cognitive or Neurological Issues'],
    'thin discharge': ['Bowel and Bladder Issues'],
    'fishy odor': ['Bowel and Bladder Issues'],
    'burning urination': ['Bowel and Bladder Issues'],
    'weak urine flow': ['Bowel and Bladder Issues'],
    'frequent urination': ['Bowel and Bladder Issues'],
    'nighttime urination': ['Bowel and Bladder Issues'],
    'incomplete emptying': ['Bowel and Bladder Issues'],
    'dribbling': ['Bowel and Bladder Issues'],
    'dark urine': ['Bowel and Bladder Issues', 'Bleeding or Blood-Related Symptoms'],
    'overeating': ['Appetite and Weight Changes'],
    'guilt': ['Mood and Behavioral Change'],
    'shame': ['Mood and Behavioral Change'],
    'distress': ['Mood and Behavioral Change'],
    'stomach pain': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'mood swings': ['Mood and Behavioral Change'],
    'mania': ['Mood and Behavioral Change'],
    'depression': ['Mood and Behavioral Change'],
    'energy changes': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'impulsive behavior': ['Mood and Behavioral Change'],
    'blood in urine': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'pain during urination': ['Bowel and Bladder Issues', 'Localized Pain'],
    'chills': ['Temperature Regulation Issues'],
    'fractures': ['Mobility and Muscular Issues', 'Bleeding or Blood-Related Symptoms'],
    'blood in stool': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'changes in bowel habits': ['Bowel and Bladder Issues'],
    'leakage': ['Bowel and Bladder Issues'],
    'urgency': ['Bowel and Bladder Issues'],
    'diarrhea': ['Bowel and Bladder Issues'],
    'no symptoms (common)': ['Miscellaneous'],
    'mucus in stool': ['Bowel and Bladder Issues'],
    'bowel habit changes': ['Bowel and Bladder Issues'],
    'no brain activity': ['Cognitive or Neurological Issues'],
    'unresponsive pupils': ['Cognitive or Neurological Issues'],
    'no breathing': ['Respiratory Issues'],
    'reflex absence': ['Cognitive or Neurological Issues'],
    'headaches': ['Localized Pain', 'Cognitive or Neurological Issues'],
    'seizures': ['Cognitive or Neurological Issues'],
    'vision changes': ['Vision and Hearing Issues'],
    'balance issues': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'personality changes': ['Mood and Behavioral Change', 'Cognitive or Neurological Issues'],
    'nipple discharge': ['Miscellaneous'],
    'skin dimpling': ['Skin Irritation or Abnormalities'],
    'persistent cough': ['Respiratory Issues'],
    'mucus': ['Respiratory Issues', 'Gastrointestinal Discomfort'],
    'chest discomfort': ['Localized Pain', 'Cardiac Symptoms', 'Respiratory Issues'],
    'weight changes': ['Appetite and Weight Changes'],
    'tooth damage': ['Miscellaneous'],
    'dehydration': ['Temperature Regulation Issues', 'Fatigue or Low Energy'],
    'foot pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'flushing': ['Skin Irritation or Abnormalities', 'Temperature Regulation Issues'],
    'swollen limbs': ['Localized Swelling'],
    'hand numbness': ['Cognitive or Neurological Issues', 'Sensory Issues'],
    'tingling': ['Cognitive or Neurological Issues', 'Sensory Issues'],
    'difficulty gripping': ['Mobility and Muscular Issues'],
    'throat mucus': ['Respiratory Issues'],
    'headache': ['Localized Pain', 'Cognitive or Neurological Issues'],
    'loss of smell': ['Sensory Issues', 'Cognitive or Neurological Issues'],
    'warmth': ['Temperature Regulation Issues'],
    'blisters': ['Skin Irritation or Abnormalities'],
    'movement difficulties': ['Mobility and Muscular Issues'],
    'stiff muscles': ['Mobility and Muscular Issues'],
    'delayed milestones': ['Developmental Issues'],
    'abnormal bleeding': ['Bleeding or Blood-Related Symptoms'],
    'leg swelling': ['Localized Swelling'],
    'neck pain': ['Localized Pain'],
    'deformity': ['Developmental Issues', 'Mobility and Muscular Issues'],
    'itchy rash': ['Skin Irritation or Abnormalities'],
    'tiredness': ['Fatigue or Low Energy'],
    'loss of appetite': ['Appetite and Weight Changes'],
    'blistering': ['Skin Irritation or Abnormalities'],
    'skin ulcers': ['Skin Irritation or Abnormalities'],
    'muscle pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'poor concentration': ['Cognitive or Neurological Issues'],
    'sleep issues': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'night sweats': ['Temperature Regulation Issues'],
    'ongoing pain': ['Localized Pain'],
    'sleep problems': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'decreased mobility': ['Mobility and Muscular Issues'],
    'oily stools': ['Gastrointestinal Discomfort', 'Bowel and Bladder Issues'],
    'abdominal swelling': ['Localized Swelling', 'Gastrointestinal Discomfort'],
    'anemia': ['Bleeding or Blood-Related Symptoms'],
    'lip blisters': ['Skin Irritation or Abnormalities'],
    'unresponsiveness': ['Cognitive or Neurological Issues'],
    'no voluntary movement': ['Cognitive or Neurological Issues', 'Mobility and Muscular Issues'],
    'no wakefulness': ['Cognitive or Neurological Issues'],
    'sore throat': ['Respiratory Issues', 'Localized Pain'],
    'heart murmur': ['Cardiac Symptoms'],
    'cyanosis': ['Skin Irritation or Abnormalities', 'Cardiac Symptoms'],
    'tearing': ['Sensory Issues', 'Vision and Hearing Issues'],
    'infrequent stools': ['Bowel and Bladder Issues'],
    'hard stools': ['Bowel and Bladder Issues'],
    'straining': ['Mobility and Muscular Issues', 'Bowel and Bladder Issues'],
    'breathlessness': ['Respiratory Issues', 'Cardiac Symptoms'],
    'brain fog': ['Cognitive or Neurological Issues'],
    'heart palpitations': ['Cardiac Symptoms'],
    'pain with breathing': ['Respiratory Issues', 'Localized Pain'],
    'dry throat': ['Skin Irritation or Abnormalities', 'Respiratory Issues'],
    'barking cough': ['Respiratory Issues'],
    'hoarseness': ['Respiratory Issues'],
    'stridor': ['Respiratory Issues'],
    'salty sweat': ['Skin Irritation or Abnormalities', 'Temperature Regulation Issues'],
    'cloudy urine': ['Bowel and Bladder Issues'],
    'hearing loss': ['Vision and Hearing Issues'],
    'vision loss': ['Vision and Hearing Issues'],
    'communication difficulty': ['Cognitive or Neurological Issues'],
    'isolation': ['Mood and Behavioral Change'],
    'leg pain': ['Localized Pain'],
    'thirst': ['Miscellaneous'],
    'dry mouth': ['Skin Irritation or Abnormalities'],
    'agitation': ['Mood and Behavioral Change'],
    'hallucinations': ['Cognitive or Neurological Issues'],
    'drowsiness': ['Fatigue or Low Energy'],
    'toothache': ['Localized Pain'],
    'bad breath': ['Miscellaneous'],
    'jaw pain': ['Localized Pain'],
    'sadness': ['Mood and Behavioral Change'],
    'loss of interest': ['Mood and Behavioral Change'],
    'sleep changes': ['Mood and Behavioral Change', 'Fatigue or Low Energy'],
    'burning': ['Localized Pain'],
    'blurred vision': ['Vision and Hearing Issues'],
    'floaters': ['Vision and Hearing Issues'],
    'eye pain': ['Localized Pain', 'Vision and Hearing Issues'],
    'loose stools': ['Bowel and Bladder Issues'],
    'itchy patches': ['Skin Irritation or Abnormalities'],
    'dry skin': ['Skin Irritation or Abnormalities'],
    'unsteadiness': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'intellectual disability': ['Developmental Issues', 'Cognitive or Neurological Issues'],
    'low muscle tone': ['Mobility and Muscular Issues', 'Developmental Issues'],
    'flat facial profile': ['Developmental Issues'],
    'short stature': ['Developmental Issues'],
    'heart defects': ['Cardiac Symptoms', 'Developmental Issues'],
    'dry tongue': ['Skin Irritation or Abnormalities'],
    'difficulty swallowing': ['Cognitive or Neurological Issues', 'Gastrointestinal Discomfort'],
    'cracked lips': ['Skin Irritation or Abnormalities'],
    'choking': ['Respiratory Issues', 'Gastrointestinal Discomfort'],
    'coughing': ['Respiratory Issues'],
    'involuntary movements': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'muscle spasms': ['Mobility and Muscular Issues'],
    'ear pain': ['Localized Pain', 'Vision and Hearing Issues'],
    'fluid drainage': ['Bowel and Bladder Issues', 'Infections'],
    'ear fullness': ['Vision and Hearing Issues'],
    'tinnitus': ['Vision and Hearing Issues'],
    'vaginal bleeding': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'shoulder pain': ['Localized Pain'],
    'growth delay': ['Developmental Issues'],
    'low-set ears': ['Developmental Issues'],
    'clenched fists': ['Mobility and Muscular Issues', 'Developmental Issues'],
    'feeding issues': ['Gastrointestinal Discomfort'],
    'developmental delays': ['Developmental Issues'],
    'infertility': ['Miscellaneous'],
    'loss of awareness': ['Cognitive or Neurological Issues'],
    'staring spells': ['Cognitive or Neurological Issues'],
    'difficulty maintaining erection': ['Miscellaneous'],
    'reduced libido': ['Mood and Behavioral Change'],
    'stress': ['Mood and Behavioral Change'],
    'diarrhea (bloody)': ['Bowel and Bladder Issues', 'Bleeding or Blood-Related Symptoms'],
    'stomach cramps': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'blurry vision': ['Vision and Hearing Issues'],
    'eye redness': ['Vision and Hearing Issues', 'Skin Irritation or Abnormalities'],
    'eye bulge': ['Vision and Hearing Issues', 'Localized Swelling'],
    'weight loss/gain': ['Appetite and Weight Changes'],
    'hair thinning': ['Hair and Nail Abnormalities'],
    'excessive gas': ['Gastrointestinal Discomfort'],
    'belching': ['Gastrointestinal Discomfort'],
    'shaking': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'stiffening': ['Mobility and Muscular Issues'],
    'loss of consciousness': ['Cognitive or Neurological Issues'],
    'throat tightness': ['Respiratory Issues', 'Localized Pain'],
    'discomfort swallowing': ['Gastrointestinal Discomfort', 'Localized Pain'],
    'lump sensation': ['Localized Swelling'],
    'throat clearing': ['Respiratory Issues'],
    'muscle aches': ['Localized Pain', 'Mobility and Muscular Issues'],
    'widespread pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'poor sleep': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'memory issues': ['Cognitive or Neurological Issues'],
    'poor growth': ['Developmental Issues'],
    'facial abnormalities': ['Developmental Issues'],
    'learning difficulties': ['Cognitive or Neurological Issues', 'Developmental Issues'],
    'hives': ['Skin Irritation or Abnormalities'],
    'anaphylaxis': ['Respiratory Issues', 'Cardiac Symptoms', 'Miscellaneous'],
    'leg deformity': ['Developmental Issues'],
    'reduced motion': ['Mobility and Muscular Issues'],
    'speech problems': ['Cognitive or Neurological Issues'],
    'thickened nails': ['Hair and Nail Abnormalities'],
    'discoloration': ['Skin Irritation or Abnormalities'],
    'crumbling edges': ['Hair and Nail Abnormalities'],
    'lump': ['Localized Swelling'],
    'wrist pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'heartburn': ['Gastrointestinal Discomfort'],
    'regurgitation': ['Gastrointestinal Discomfort'],
    'flu symptoms': ['Infections'],
    'sores': ['Skin Irritation or Abnormalities'],
    'bumps': ['Skin Irritation or Abnormalities', 'Localized Swelling'],
    'discomfort': ['Localized Pain'],
    'swollen glands': ['Localized Swelling', 'Infections'],
    'elbow pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'reduced grip strength': ['Mobility and Muscular Issues'],
    'hip pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'loose teeth': ['Miscellaneous'],
    'mucus discharge': ['Respiratory Issues', 'Gastrointestinal Discomfort'],
    'mouth sores': ['Skin Irritation or Abnormalities'],
    'visible lice': ['Infections'],
    'red bumps': ['Skin Irritation or Abnormalities'],
    'scalp irritation': ['Skin Irritation or Abnormalities'],
    'secondary infection': ['Infections'],
    'pressure': ['Localized Pain'],
    'sensitivity to light': ['Sensory Issues', 'Vision and Hearing Issues'],
    'muffled sounds': ['Vision and Hearing Issues'],
    'difficulty understanding speech': ['Cognitive or Neurological Issues'],
    'ringing': ['Vision and Hearing Issues'],
    'arm pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'slow heartbeat': ['Cardiac Symptoms'],
    'weight gain': ['Appetite and Weight Changes'],
    'fluttering': ['Cardiac Symptoms'],
    'pounding heartbeat': ['Cardiac Symptoms'],
    'nosebleed': ['Bleeding or Blood-Related Symptoms'],
    'red welts': ['Skin Irritation or Abnormalities'],
    'swollen nodes': ['Localized Swelling', 'Infections'],
    'movement problems': ['Mobility and Muscular Issues'],
    'excessive sweating': ['Temperature Regulation Issues'],
    'skin irritation': ['Skin Irritation or Abnormalities'],
    'odor': ['Miscellaneous'],
    'hunger': ['Appetite and Weight Changes'],
    'dry cough': ['Respiratory Issues'],
    'clubbing of fingers': ['Skin Irritation or Abnormalities', 'Respiratory Issues'],
    'red sores': ['Skin Irritation or Abnormalities'],
    'crusting': ['Skin Irritation or Abnormalities'],
    'infection': ['Infections'],
    'pus': ['Skin Irritation or Abnormalities', 'Infections'],
    'irregular periods (female)': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'low sperm count (male)': ['Miscellaneous'],
    'hormonal changes': ['Miscellaneous'],
    'bloody stools': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'daytime sleepiness': ['Fatigue or Low Energy'],
    'scaling': ['Skin Irritation or Abnormalities'],
    'irritation': ['Skin Irritation or Abnormalities'],
    'soreness': ['Localized Pain'],
    'frequent dislocations': ['Mobility and Muscular Issues'],
    'purple skin lesions': ['Skin Irritation or Abnormalities'],
    'severe pain': ['Localized Pain'],
    'balance problems': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'gas': ['Gastrointestinal Discomfort'],
    'sudden pain': ['Localized Pain'],
    'muscle stiffness': ['Mobility and Muscular Issues'],
    'purplish bumps': ['Skin Irritation or Abnormalities'],
    'heaviness in legs': ['Mobility and Muscular Issues'],
    'skin sensitivity': ['Skin Irritation or Abnormalities', 'Sensory Issues'],
    'low energy': ['Fatigue or Low Energy'],
    'lower back pain': ['Localized Pain'],
    'bullseye rash': ['Skin Irritation or Abnormalities'],
    'facial paralysis': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'heaviness': ['Mobility and Muscular Issues'],
    'tight skin': ['Skin Irritation or Abnormalities'],
    'genital sores': ['Skin Irritation or Abnormalities'],
    'rectal pain': ['Localized Pain', 'Bowel and Bladder Issues'],
    'red eyes': ['Vision and Hearing Issues', 'Skin Irritation or Abnormalities'],
    'stiff neck': ['Localized Pain', 'Mobility and Muscular Issues'],
    'light sensitivity': ['Sensory Issues', 'Vision and Hearing Issues'],
    'ear pressure': ['Vision and Hearing Issues'],
    'hot flashes': ['Temperature Regulation Issues'],
    'sleep disturbances': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'vaginal dryness': ['Skin Irritation or Abnormalities', 'Bowel and Bladder Issues'],
    'visual aura': ['Vision and Hearing Issues'],
    'tissue discharge': ['Bowel and Bladder Issues'],
    'twitching': ['Mobility and Muscular Issues'],
    'speech difficulty': ['Cognitive or Neurological Issues'],
    'breathing difficulty': ['Respiratory Issues'],
    'painful sores': ['Skin Irritation or Abnormalities', 'Localized Pain'],
    'difficulty eating': ['Gastrointestinal Discomfort'],
    'white patches': ['Skin Irritation or Abnormalities'],
    'coordination issues': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'bladder issues': ['Bowel and Bladder Issues'],
    'faking illness': ['Mood and Behavioral Change'],
    'exaggeration of symptoms': ['Mood and Behavioral Change'],
    'frequent doctor visits': ['Miscellaneous'],
    'unexplained symptoms': ['Miscellaneous'],
    'frequent falls': ['Mobility and Muscular Issues'],
    'breathing issues': ['Respiratory Issues'],
    'drooping eyelids': ['Mobility and Muscular Issues', 'Vision and Hearing Issues'],
    'facial pain': ['Localized Pain'],
    'lump in neck': ['Localized Swelling'],
    'nasal bleeding': ['Bleeding or Blood-Related Symptoms', 'Respiratory Issues'],
    'congestion': ['Respiratory Issues'],
    'snoring': ['Respiratory Issues'],
    'repetitive thoughts': ['Mood and Behavioral Change', 'Cognitive or Neurological Issues'],
    'compulsive behaviors': ['Mood and Behavioral Change'],
    'anxiety': ['Mood and Behavioral Change'],
    'daytime fatigue': ['Fatigue or Low Energy'],
    'gasping during sleep': ['Respiratory Issues'],
    'loss of taste': ['Sensory Issues'],
    'cracking sounds': ['Vision and Hearing Issues', 'Mobility and Muscular Issues'],
    'limping': ['Mobility and Muscular Issues'],
    'joint swelling': ['Localized Swelling'],
    'knee pain': ['Localized Pain', 'Mobility and Muscular Issues'],
    'joint instability': ['Mobility and Muscular Issues'],
    'thumb pain': ['Localized Pain'],
    'height loss': ['Developmental Issues'],
    'stooped posture': ['Mobility and Muscular Issues'],
    'brittle bones': ['Mobility and Muscular Issues'],
    'urinary frequency': ['Bowel and Bladder Issues'],
    'irregular periods': ['Bleeding or Blood-Related Symptoms', 'Bowel and Bladder Issues'],
    'pelvic pressure': ['Localized Pain', 'Bowel and Bladder Issues'],
    'flaky skin': ['Skin Irritation or Abnormalities'],
    'fear of losing control': ['Mood and Behavioral Change'],
    'slow movements': ['Mobility and Muscular Issues'],
    'poor balance': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'speech changes': ['Cognitive or Neurological Issues'],
    'cleft lip': ['Developmental Issues'],
    'extra fingers or toes': ['Developmental Issues'],
    'low birth weight': ['Developmental Issues'],
    'difficulty climbing stairs': ['Mobility and Muscular Issues'],
    'abnormal discharge': ['Bowel and Bladder Issues'],
    'urinary leakage': ['Bowel and Bladder Issues'],
    'visible bulge': ['Localized Swelling'],
    'burning pain': ['Localized Pain'],
    'sensitivity': ['Sensory Issues'],
    'impulsivity': ['Mood and Behavioral Change'],
    'relationship difficulties': ['Mood and Behavioral Change'],
    'identity issues': ['Mood and Behavioral Change'],
    'emotional instability': ['Mood and Behavioral Change'],
    'stabbing pain': ['Localized Pain'],
    'paralysis': ['Mobility and Muscular Issues', 'Cognitive or Neurological Issues'],
    'acne': ['Skin Irritation or Abnormalities'],
    'breathing problems': ['Respiratory Issues'],
    'flashbacks': ['Mood and Behavioral Change'],
    'nightmares': ['Mood and Behavioral Change'],
    'emotional numbness': ['Mood and Behavioral Change'],
    'difficulty bonding': ['Mood and Behavioral Change'],
    'skin redness': ['Skin Irritation or Abnormalities'],
    'open sores': ['Skin Irritation or Abnormalities'],
    'vision difficulties': ['Vision and Hearing Issues'],
    'red patches': ['Skin Irritation or Abnormalities'],
    'nail changes': ['Hair and Nail Abnormalities'],
    'delusions': ['Cognitive or Neurological Issues', 'Mood and Behavioral Change'],
    'disorganized thoughts': ['Cognitive or Neurological Issues'],
    'red spots': ['Skin Irritation or Abnormalities'],
    'swollen legs': ['Localized Swelling'],
    'intense fear': ['Mood and Behavioral Change'],
    'avoidance behavior': ['Mood and Behavioral Change'],
    'cold fingers or toes': ['Temperature Regulation Issues', 'Skin Irritation or Abnormalities'],
    'color changes (white, blue, red)': ['Skin Irritation or Abnormalities'],
    'eye inflammation': ['Vision and Hearing Issues', 'Skin Irritation or Abnormalities'],
    'urinary problems': ['Bowel and Bladder Issues'],
    'skin rash': ['Skin Irritation or Abnormalities'],
    'leg discomfort': ['Localized Pain'],
    'crawling sensation': ['Sensory Issues'],
    'white pupil reflex': ['Vision and Hearing Issues'],
    'eye swelling': ['Localized Swelling', 'Vision and Hearing Issues'],
    'ring-shaped sores': ['Skin Irritation or Abnormalities'],
    'cracking skin': ['Skin Irritation or Abnormalities'],
    'facial redness': ['Skin Irritation or Abnormalities'],
    'visible blood vessels': ['Skin Irritation or Abnormalities'],
    'eye irritation': ['Vision and Hearing Issues'],
    'intense itching': ['Skin Irritation or Abnormalities', 'Sensory Issues'],
    'burrows in skin': ['Skin Irritation or Abnormalities'],
    'red tongue (strawberry tongue)': ['Skin Irritation or Abnormalities'],
    'emotional withdrawal': ['Mood and Behavioral Change'],
    'low mood': ['Mood and Behavioral Change'],
    'painful rash': ['Skin Irritation or Abnormalities', 'Localized Pain'],
    'burning sensation': ['Localized Pain'],
    'rapid breathing': ['Respiratory Issues'],
    'pain episodes': ['Localized Pain'],
    'dry eyes': ['Vision and Hearing Issues', 'Skin Irritation or Abnormalities'],
    'mole changes': ['Skin Irritation or Abnormalities'],
    'dark spots': ['Skin Irritation or Abnormalities'],
    'scabs': ['Skin Irritation or Abnormalities'],
    'red cheeks': ['Skin Irritation or Abnormalities'],
    'difficulty moving': ['Mobility and Muscular Issues'],
    'leg weakness': ['Mobility and Muscular Issues'],
    'bowel issues': ['Bowel and Bladder Issues'],
    'pain in upper left abdomen': ['Localized Pain', 'Gastrointestinal Discomfort'],
    'no fetal movement': ['Miscellaneous'],
    'no symptoms (sudden event)': ['Miscellaneous'],
    'withdrawal': ['Mood and Behavioral Change'],
    'hopelessness': ['Mood and Behavioral Change'],
    'self-harm': ['Mood and Behavioral Change'],
    'talking about death': ['Mood and Behavioral Change'],
    'peeling skin': ['Skin Irritation or Abnormalities'],
    'heaviness in scrotum': ['Mobility and Muscular Issues', 'Bowel and Bladder Issues'],
    'scrotal heaviness': ['Mobility and Muscular Issues', 'Bowel and Bladder Issues'],
    'anal itching': ['Skin Irritation or Abnormalities', 'Bowel and Bladder Issues'],
    'disturbed sleep': ['Fatigue or Low Energy', 'Mood and Behavioral Change'],
    'white discharge': ['Bowel and Bladder Issues'],
    'buzzing': ['Vision and Hearing Issues'],
    'hissing': ['Vision and Hearing Issues'],
    'humming': ['Vision and Hearing Issues'],
    'swollen tonsils': ['Localized Swelling'],
    'visible holes': ['Miscellaneous'],
    'difficulty chewing': ['Gastrointestinal Discomfort', 'Mobility and Muscular Issues'],
    'tics': ['Mobility and Muscular Issues'],
    'blinking': ['Mobility and Muscular Issues', 'Sensory Issues'],
    'repetitive movements': ['Mobility and Muscular Issues'],
    'vocal outbursts': ['Mood and Behavioral Change'],
    'vaginal discharge': ['Bowel and Bladder Issues'],
    'sharp shooting pain': ['Localized Pain'],
    'sensitivity to touch': ['Sensory Issues'],
    'spasms': ['Mobility and Muscular Issues'],
    'slow wound healing': ['Infections'],
    'urine leakage': ['Bowel and Bladder Issues'],
    'night-time urination': ['Bowel and Bladder Issues'],
    'wetness': ['Bowel and Bladder Issues'],
    'weak bladder control': ['Bowel and Bladder Issues'],
    'urinary difficulties': ['Bowel and Bladder Issues'],
    'abnormal color or texture': ['Skin Irritation or Abnormalities'],
    'brown discoloration': ['Skin Irritation or Abnormalities'],
    'visible veins': ['Skin Irritation or Abnormalities'],
    'aching': ['Localized Pain'],
    'color changes': ['Skin Irritation or Abnormalities'],
    'rough skin growths': ['Skin Irritation or Abnormalities'],
    'whooping sound': ['Respiratory Issues'],
    'vomiting after coughing': ['Gastrointestinal Discomfort', 'Respiratory Issues'],
    'spinning sensation': ['Cognitive or Neurological Issues'],
    'difficulty concentrating': ['Cognitive or Neurological Issues'],
}


# Process file
def replace_symptoms(input_file, output_file):
    # clear output file
    open(output_file, 'w').close()

    with open(input_file, "r") as file:
        
        for line in file:
            colon_idx = line.index(':')
            disease = line[:colon_idx]
            symptoms = line[colon_idx + 1:].strip().split(',')
            new_symptoms = []

            for symptom in symptoms:
                occassional = False
                if "(occasional)" in symptom:
                    symptom = symptom.replace("(occasional)", "").strip()
                    occassional = True

                if ":" in symptom:
                    symptom = symptom[symptom.index(':')+1:].strip()
                
                symptom = symptom.lower().strip()
                if symptom in symptom_mapping:
                    mapped_symptoms = symptom_mapping[symptom]
                    if occassional:
                        mapped_symptoms = [f"{symptom} (occasional)" for symptom in mapped_symptoms]
                    new_symptoms.extend(mapped_symptoms)
                else:
                    # print(f"Symptom '{symptom}' not found in mapping.")
                    new_symptoms.append(symptom)
                
                # if symptom == "chest pain":
                #     print(new_symptoms)

            with open(output_file, "a") as output:
                output.write(f"{disease}: {', '.join(new_symptoms)}\n")


# Example usage
input_file = "conditions_list.txt"  # Replace with your input file
output_file = "conditions_list_reduced.txt"  # Replace with your output file
replace_symptoms(input_file, output_file)

print(f"Symptoms replaced and saved to {output_file}.")
